#!/bin/bash
# Script per avviare applicazioni GUI nel desktop remoto

echo "🖥️  Guida Desktop Remoto per Centrafari"
echo "======================================"
echo ""
echo "Per usare le applicazioni GUI (tkinter):"
echo ""
echo "1️⃣  Apri il desktop remoto:"
echo "   - Vai alla tab 'PORTS' in VS Code"
echo "   - Clicca sull'icona del globo accanto a 'Desktop (noVNC) - 6080'"
echo "   - Si aprirà il desktop nel browser"
echo ""
echo "2️⃣  Nel desktop remoto, apri un terminale e esegui:"
echo "   cd /workspaces/centrafari"
echo "   python3 MW28912.py"
echo ""
echo "3️⃣  La finestra tkinter apparirà nel desktop remoto!"
echo ""
echo "📝 Credenziali VNC:"
echo "   Password: vscode"
echo ""
echo "💡 Suggerimento: Puoi anche usare questo comando per avviare direttamente:"
echo "   DISPLAY=:1 python3 MW28912.py"
echo ""
